### ISSUE TITLE
Error with HyperBackup using WebDAV to OneDrive: "Did not receive Set Token Message after First Authenticated Request Message"

### ISSUE THREAD

**Issue by trialking88** [skleeschulte/basic-to-passport-auth-http-proxy#31]
First of all: Thank you very much for this tool. It has been working great so far. Recently my backup jobs fail though. I tried to figure it out by myself, but I haven't found any solution. It might be an issue with the proxy.

**Description:**
I am encountering an error while using HyperBackup to back up my Synology DiskStation to OneDrive via WebDAV. I am using the basic-to-passport-auth-http-proxy Docker container. Recently, I started receiving the following error messages:

```
2024/12/07 20:31:06 stdout 2024-12-07T19:31:06.659Z proxy:error [28920786/4570] Sending error response: 500 Did not receive Set Token Message after First Authenticated Request Message

2024/12/07 20:31:06 stdout 2024-12-07T19:31:06.659Z proxy:error Did not receive Set Token Message after First Authenticated Request Message
```

**I have verified the following:**
[skleeschulte-basic-to-passport-auth-http-proxy-1.txt](https://github.com/user-attachments/files/18049750/skleeschulte-basic-to-passport-auth-http-proxy-1.txt)

- Proxy configuration is verified and appears correct.
- Docker container is up-to-date and functioning.
- HyperBackup is updated to the latest version.
- OneDrive account is functioning with no restrictions or issues.

**Full Log is attached, CUID is modified**
[skleeschulte-basic-to-passport-auth-http-proxy-1.txt](https://github.com/user-attachments/files/18049752/skleeschulte-basic-to-passport-auth-http-proxy-1.txt)

**Steps to Reproduce:**
- Configure backup to OneDrive using WebDAV with the basic-to-passport-auth-http-proxy Docker container.
- Following the instructions from here: https://rays-blog.de/2019/07/17/310/backup-to-microsoft-onedrive-with-synologys-hyper-backup/
- Run the backup job.

**Additional Information:**
- Synology DiskStation Model: DS918+
- HyperBackup Version: 4.1.2-4039

**Comment by clintonbale** [comment]
Getting the same issue on my Synology since December 7th

DSM version: DSM 7.2.2-72806 Update 2
HyperBackup Version: 4.1.2-4039

**Comment by haydn-gmail** [comment]
Getting the same issue on my Synology since October 4, 2024
DSM version: DSM 7.2.2-72806 Update 2
HyperBackup Version: 4.1.2-4039
Synology DiskStation Model: DS1522+

My Hyper backup task to OneDrive worked great until Hyper Backup shows "Backup Destination Corrupted. Restore only". This error happens when Hyper Backup found corrupted files in backup during periodic integrity check, and can usually be fixed by deleting the failed task then create an new task relinking to the original task. 

However, since October 2024, there has been a chance that Hyper Backup could no longer connect to the same OneDrive account via WebDAV (with basic-to-passport-auth-http-proxy).  After entering correct authentication credential, Hyper backup would show error: "Could not complete the operation, possibly because of the network connection is unstable, or system is busy. Please try again."  Checked that network is fine, system is not busy. 

The basic-to-passport-auth-http-proxy container's log shows two error entries: "proxy:error . Sending error response: 500 Did not receive Set Token Message after First Authenticated Request Message" "proxy: error Did not receive Set Token Message after First Authenticated Request Message"

**Comment by seyfidin** [comment]
Did you not see #29 ? This project is dead, you need to switch to rclone.
