### ISSUE TITLE
Cache overflowed while caching data

### ISSUE THREAD

**Issue by cosyd** [skleeschulte/basic-to-passport-auth-http-proxy#4]
In the log after
"Proxy request: PUT /...."
I am getting the error 
"RequestBodyCache: Cache overflowed while caching data"

This is a Synology Diskstation syncing to Onedrive via Hyperbackup. Smaller backups work fine, on large backups it seems to get this hickup and gets stuck. Perhaps a large file issue?

**Comment by carbone15** [comment]
Hello,
I have, I think the same problem. With big/long backup it stop with error "sending error response: 503 passport authentication was successfull, but the proxy server cannot repeat the original client request with authorization because the client request body length exceeds the request body cache size of 2048KB."
This dev was a goog idea but if I can't backup mys "full" NAS, not so usefull :(

**Comment by cosyd** [comment]
I played around with a few tweaks in the code of this solution but none worked, so I ended up with a workaround:
I downloaded the entire backup vault to the synology local file system and made it available as WebDAV with the synology built in WebDAV Server package. Now I re-linked the Hyperbackup task to the local copy of the vault via WebDAV. That way I continue to have incremental backups.
I then also configured CloudSync to mirror the vault folder into OneDrive to have it saved remotely in case of disk failure/theft/fire.

**Comment by carbone15** [comment]
Thanks for this solution, I don't like to use cloud to sync :(. I tried to install with node js and change into the code, but I have the same error.
So I will just stop to use this solution:(

**Comment by Vimse** [comment]
Hi,
I also get this "Restore only. Destination corrupted." error in  Hyper Backup after following the guide. The solution works for a while, before the message appears. A solution would be greatly appreciated!

**Comment by skleeschulte** [comment]
The error messages mentioned first in this issue are expected: The 503 response tells the WebDAV client that uses the proxy, that the service is temporarily unavailable and the request should be repeated. "RequestBodyCache: Cache overflowed while caching data" is the root cause for the 503 error and is logged only in debug mode. This error occurs, when the proxy needs to (re-)authenticate to OneDrive while uploading a file larger than 2048KB. The authentication is still successfull, and next time the WebDAV client tries to upload the file it should work.

"Restore only. Destination corrupted." is probably linked to #11 .
